services:
  sandbox:
    container_name: ai-coder-sandbox
    build: ./docker/sandbox
    volumes:
      - sandbox_data:/home/agentuser
    stdin_open: true
    tty: true
    working_dir: /home/agentuser/project
    
  mongodb:
    container_name: ai-coder-mongodb
    build: ./docker/mongodb
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017

volumes:
  sandbox_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/adamsiler/projects/ai-coder-sandbox
  mongodb_data:
